target 'PostHelper' do
use_frameworks!
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
#pod 'DKImagePickerController'
pod 'Fabric'
pod 'TwitterKit'
pod 'TwitterCore'
#pod 'TwitterVideoUploader'
end
